# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Array Indexing/Slicing

- Basic Indexing

In [2]:
a1 = np.array([2,4,6,8,10])
a1[2]

6

- How to get last three digit of the array

In [3]:
a1[2:]

array([ 6,  8, 10])

- How to get first three element of the array

In [4]:
a1[:-2]

array([2, 4, 6])

- How to get between numbers from the array

In [5]:
a1[1:-2]

array([4, 6])

- Important note here is The first element corresponds to the indexing from left side while -1 or -2 correspend from the right side (other side)
- For example if i want to get rid of 2 and 10 from array 2 is at index 0 and 10 is at index 4 while in negative term it is on [0:] means we leave it empty 

In [6]:
a1[1:]

array([ 4,  6,  8, 10])

- Boolen Indexing

In [7]:
a1>5

array([False, False,  True,  True,  True])

In [8]:
a1 [a1>5]

array([ 6,  8, 10])

#### Fiding Name in the list with the starting letter only 

In [9]:
name = np.array(["Hasnat", "Humayun", "Kainat", "Moeed", "Omer"])

- Here we use Lambda function "lambda s: s[0]" it is a function which take the whole "s" argument and return with the first index letter

In [10]:
f = lambda s: s[0]
s = "Dota 2"
f(s)

'D'

- np.vectorize is sort of the for loop which will go into the array created of the names and apply lambda function on it and this whole is an array as well

In [11]:
np.vectorize(lambda s: s[0])(name)

array(['H', 'H', 'K', 'M', 'O'], dtype='<U1')

- Apply above concepts

In [12]:
first_name = np.vectorize(lambda s: s[0])(name) == "H"
first_name

array([ True,  True, False, False, False])

In [13]:
name [first_name]

array(['Hasnat', 'Humayun'], dtype='<U7')

#### Finding all the element in the array that are divisible by 4

In [14]:
x = np.arange(0,20,2)
x[x%4==0]

array([ 0,  4,  8, 12, 16])