# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Multi-Dimensional Arrays

Creating multi dimensional arrays

In [2]:
a1=np.array([[1,3,7],[2,4,6],[7,4,3]])

In [3]:
a1

array([[1, 3, 7],
       [2, 4, 6],
       [7, 4, 3]])

- Operation Works in similar way

In [4]:
a1*2

array([[ 2,  6, 14],
       [ 4,  8, 12],
       [14,  8,  6]])

In [5]:
2/a1

array([[2.        , 0.66666667, 0.28571429],
       [1.        , 0.5       , 0.33333333],
       [0.28571429, 0.5       , 0.66666667]])

- Can turn any n-dimensional array to a 1d array using ravel() method

it converts 2d 3d array into 1d array very usefull

In [6]:
a2 = a1.ravel()
a2

array([1, 3, 7, 2, 4, 6, 7, 4, 3])

- Boolen Indexing same as 1d array

In [7]:
a1>4

array([[False, False,  True],
       [False, False,  True],
       [ True, False, False]])

- 2d Randon Array

In [8]:
a2 = np.random.randn(3,3)
a2

array([[ 1.25694832, -0.5872038 ,  0.04214083],
       [ 1.06165024, -0.2468944 ,  0.36822449],
       [ 1.53013572,  1.70994997,  0.35217901]])

In [9]:
a2[a1>4]

array([0.04214083, 0.36822449, 1.53013572])

- Element Indexing

a[[rows] [column]]

In [10]:
a1

array([[1, 3, 7],
       [2, 4, 6],
       [7, 4, 3]])

-Acess Rows

In [11]:
a1[1]

array([2, 4, 6])

- Acess Column

In [12]:
a1[:,2]

array([7, 6, 3])

- a1[:,2] it states that take all rows and get third element because we put 2 there if it is 1 then it take second and vice versa 
- if we modify if to a1[1:,2] it will start from row number 2 and take column from the row number 2 

In [13]:
a1[1:,2]

array([6, 3])

In [14]:
a1[0][1]

3

- From array get 2,4 and 7,4 

- the a[1:, ] says go to the second row and take all the element while :2 says take only the first two element of each rows

In [15]:
a1[1:,:2]

array([[2, 4],
       [7, 4]])

- Here a1[0: ] says take all the element starting from the first row it can also be left blank
- And a1[:-1] says ignore the last row that is why - sign is used to ignore the last row
- And a1[,:2] denotes take only first two element from each row

In [16]:
a1[0:-1,:2]

array([[1, 3],
       [2, 4]])

- Here we can see that a1[:-1] does the same takes first two row and -1 ignore the last rows while now [1:] say ignore the first element and take last two

In [17]:
a1[:-1,1:]

array([[3, 7],
       [4, 6]])